version: '3.7'

services:

    db:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    php:
        build: ./docker/container/php-fpm
        # command: sh -c 'cd /var/www/symfony composer install'
        ports:
            - 9000:9001
        volumes:
            - ./symfony:/var/www/symfony:cached
            - ./docker/logs/symfony:/var/www/symfony/var/log:cached
        links:
            - db

    nginx:
        build: ./docker/container/nginx
        ports:
            - 80:80
        links:
            - php
            - react
        volumes:
            - ./docker/logs/nginx:/var/log/nginx:cached
            - ./symfony:/var/www/symfony:cached
            - ./react:/var/www/react

    react:
        build: ./react
        # command: sh -c 'cd /var/www/react npm install' #sh -c 'cd /var/www/react npm run-script build'
        volumes:
            - ./react:/var/www/react
            - ./react/node_modules:/var/www/react/node_modules
        ports:
            - 3001:3000
        environment:
            - NODE_ENV=development
