version: '3.7'

services:

    db:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    php:
        build: ./docker/container/php-fpm
        ports:
            - 9000:9001
        volumes:
            - ./laravel:/var/www/laravel:cached
            - ./docker/logs/laravel:/var/www/laravel/storage/logs:cached
        links:
            - db

    nginx:
        build: ./docker/container/nginx
        ports:
            - 80:80
        links:
            - php
            - node_client
        volumes:
            - ./docker/logs/nginx:/var/log/nginx:cached
            - ./laravel:/var/www/laravel:cached
            - ./node/client:/var/www/node_client

    node_client:
        build: ./node/client
        volumes:
            - ./node/client:/var/www/node_client
            - ./node/client/node_modules:/var/www/node_client/node_modules
        ports:
            - 3001:3000
        environment:
            - NODE_ENV=development
