security:
    encoders:
        App\UserBundle\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\UserBundle\Entity\User
                property: email

    firewalls:
        user:
            pattern: ^/auth
            stateless: true
            guard:
                authenticators:
                    - App\UserBundle\Security\TokenAuthenticator
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
